"""Bounded, disposable font preparation; never terminate the PDF owner.
SPDX-License-Identifier: AGPL-3.0-or-later
"""
from functools import lru_cache
from pathlib import Path
import os, pickle, re, subprocess, sys, tempfile, time

FONT_TIMEOUT = 15
CANCEL_EVENT = None


def snapshot_fonts(document, page):
    """Copy only font programs/maps, not the PDF or its images, into the job."""
    entries = document[page].get_fonts(full=True)
    programs, keys, streams = {}, {}, {}
    def key(xref, name):
        value = document.xref_get_key(xref, name)
        keys[xref, name] = value
        return value
    for entry in entries:
        xref = entry[0]
        programs[xref] = document.extract_font(xref)
        if not xref: continue
        key(xref, 'Encoding')
        kind, value = key(xref, 'ToUnicode')
        if kind == 'xref':
            ref = int(value.split()[0]); streams[ref] = document.xref_stream(ref)
        kind, value = key(xref, 'DescendantFonts')
        if kind == 'array':
            for ref in re.findall(r'(\d+)\s+0\s+R', value):
                kind, value = key(int(ref), 'CIDToGIDMap')
                if kind == 'xref':
                    ref = int(value.split()[0]); streams[ref] = document.xref_stream(ref)
    traces = [{'font': span['font'], 'chars': [(cp, gid) for cp, gid, *_ in span['chars']]}
              for span in document[page].get_texttrace()]
    return {'entries': entries, 'programs': programs, 'keys': keys, 'streams': streams, 'traces': traces}


class FontSource:
    def __init__(self, source): self.source = source
    def __getitem__(self, page): return self
    def get_fonts(self, full=True): return self.source['entries']
    def extract_font(self, xref): return self.source['programs'][xref]
    def xref_get_key(self, xref, name): return self.source['keys'].get((xref, name), ('null', 'null'))
    def xref_stream(self, xref): return self.source['streams'][xref]
    def get_texttrace(self): return self.source['traces']


def prepare(payload):
    import fitz
    from .fonts import installed_fonts, original_font, font_bytes, qt_font, has_text
    if payload['operation'] == 'list': return {'fonts': installed_fonts()}
    source = FontSource(payload['snapshot']); result = []
    for name, text in payload['requests'].items():
        try:
            partial = False
            if payload['source'] == 'original':
                try: data = original_font(source, 0, name, text)
                except ValueError:
                    # No program covers every character. Keep the closest
                    # original program; the editor shows only the missing
                    # characters in a fallback font instead of refusing.
                    data = original_font(source, 0, name, ''); partial = True
            else:
                data = font_bytes(payload['path']) if payload['path'] else fitz.Font('korea').buffer
                partial = not has_text(data, text)
            prepared, family = qt_font(data)
            result.append({'name': name, 'data': prepared, 'family': family, 'error': '', 'partial': partial})
        except Exception as exc:
            result.append({'name': name, 'data': b'', 'family': '', 'error': str(exc)})
    return {'fonts': result}


def run_job(payload, timeout=FONT_TIMEOUT):
    with tempfile.TemporaryDirectory(prefix='yoondf-font-') as folder:
        request, response = Path(folder)/'request', Path(folder)/'response'
        request.write_bytes(pickle.dumps(payload, protocol=5))
        args = ([sys.executable, '--yoondf-font-job'] if getattr(sys, 'frozen', False)
                else [sys.executable, '-m', 'bichaek.font_jobs'])
        run = subprocess.Popen(args+[str(request), str(response)],
                cwd=Path(__file__).resolve().parent.parent, stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                creationflags=subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0)
        deadline = time.monotonic()+timeout
        try:
            while run.poll() is None:
                if CANCEL_EVENT is not None and CANCEL_EVENT.is_set():
                    raise ValueError('프로그램 종료로 글꼴 확인을 취소했어요.')
                remaining = deadline-time.monotonic()
                if remaining <= 0:
                    raise ValueError('글꼴 확인 시간이 초과됐어요. 원문은 유지돼요. 다른 글꼴을 선택하거나 취소 후 다시 시도해 주세요.')
                try: run.wait(timeout=min(.1, remaining))
                except subprocess.TimeoutExpired: pass
        finally:
            if run.poll() is None: run.kill()
            run.wait()
        if run.returncode or not response.is_file():
            raise ValueError('글꼴 처리기가 종료됐어요. 다른 글꼴을 선택하거나 취소 후 다시 시도해 주세요.')
        result = pickle.loads(response.read_bytes())
        if 'error' in result: raise ValueError(result['error'])
        return result


@lru_cache(maxsize=1)
def font_catalog(): return run_job({'operation': 'list'})


def main(args):
    # These paths are generated by this application in a private temporary directory.
    request, response = map(Path, args)
    try: result = prepare(pickle.loads(request.read_bytes()))
    except Exception as exc: result = {'error': str(exc)}
    response.write_bytes(pickle.dumps(result, protocol=5))


if __name__ == '__main__': main(sys.argv[1:])
